### ISSUE TITLE
Warn about useless `abstr` modifier

### ISSUE THREAD

**Issue by forell** [fram-lang/dbl#71]
Within a recursive block marked as `pub`, the `abstr` modifier on a data type has no effect, since the public visibility is propagated to the constructors regardless. This should probably trigger a warning, as it might not be the programmer's intention.
```
module M
  pub rec
    abstr data T = C
  end
end
```

**Comment by ppolesiuk** [comment]
Additional check should be added in `DData` case in `Parser.Desugar.tr_def`.
